#!/bin/bash
#
# Regards, the Alveare Solutions society.
#
declare -A SC_DEFAULT
declare -A SC_LIB
declare -A SC_SOURCE
declare -A SC_CARGO

# [ NOTE ]: Absolute directory path the current file is in.
SC_DIRECTORY="$(
    cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd
)"
CONF_FILE_PATH="$SC_DIRECTORY/conf/scorpion-client.conf"

if [ ! -f "$CONF_FILE_PATH" ]; then
    echo "[ WARNING ]: Config file ($CONF_FILE_PATH) not found."
    return 1
else
    source "$CONF_FILE_PATH"
fi

for script in ${!SC_SOURCE[@]}; do
    source ${SC_SOURCE[$script]}
    if [ $? -ne 0 ]; then
        echo "[ NOK ]: Something went wrong."\
            "Could not load ($script) script."
    else
        echo "[ OK ]: Successfully loaded ($script) script."
    fi
done

for library in ${!SC_LIB[@]}; do
    source ${SC_LIB[$library]}
    if [ $? -ne 0 ]; then
        echo "[ NOK ]: Something went wrong."\
            "Could not load ($library) library."
    else
        echo "[ OK ]: Successfully loaded ($library) library."
    fi
done

# MISCELLANEOUS

function init_scorpion_client () {
    project_setup
    display_banners
    init_menu 'MainController'
    return $?
}

init_scorpion_client $@
exit $?
